version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.7.0
    environment:
      # limit heap size to 3GB 
      NODE_OPTIONS: '--max-old-space-size=3072'
      YARN_TASK_POOL_CONCURRENCY: 1
      YARN_ENABLE_INLINE_BUILDS: true
    steps:
      - checkout
      - run: yarn --version
      - run: yarn install
      - run: ls node_modules
