version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.7.0
    environment:
      # limit heap size to 3GB 
      NODE_OPTIONS: '--max-old-space-size=3072'
      TASK_POOL_CONCURRENCY: 1
      YARN_LOG_LEVEL: verbose
    steps:
      - checkout
      - run: yarn --version
      - run: |
          yarn install --verbose
      - run: ls node_modules
